image: kaiwinter/docker-java8-maven

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths: 
      - maven
    name: "emc-$CI_COMMIT_SHORT_SHA-snapshot"